name: Continuous integration
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel
jobs:
  smoke:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive --force
      - run: docker build . -t local-erigon
      - run: docker run --cidfile cont.id local-erigon "erigon --datadir data --private.api.addr localhost:9090 && rpcdaemon --datadir data --private.api.addr --http.api eth,web3,net,debug,trace"

