name: Continuous integration
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel
jobs:
  smoke:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive --force
      - run: docker build . -t local-erigon
      - run: docker create local-erigon > cont.id
      - run: docker start `cat cont.id`
      - run: docker exec -d `cat cont.id` erigon --datadir data --private.api.addr localhost:9090
      - run: docker exec -d `cat cont.id` rpcdaemon --datadir data --private.api.addr --http.api eth,web3,net,debug,trace
