name: Continuous integration
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel
jobs:
  smoke:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive --force
      - run: docker build . -t local-erigon
      - run: docker run --cidfile cont.id local-erigon erigon --datadir data --private.api.addr localhost:9090
      - run: docker exec `cat cont.id` rpcdaemon --datadir data --private.api.addr localhost:9090 --http.api eth,net,web3
